"""PUMA export column order, aliases, and parameter metadata (v3 spec)."""

from __future__ import annotations

from typing import Any, Dict, List, Optional, Tuple

# From audit — typical column order in PUMA exports
PUMA_COLUMNS_ORDERED: List[str] = [
    "AVL_INDEP_TIME",
    "PRNAME",
    "DATUM",
    "ZEIT",
    "VERSIONT",
    "N",
    "MD",
    "P4_A1ABS",
    "T2_I1",
    "CAIR_P1",
    "CAIR_T1",
    "CAIR_H1",
    "TW_R",
    "TKR_Z",
    "CRP_SEDC",
    "CRP_IEDC",
    "SB_I_EDC",
    "INJCHAR",
    "MPI1_EDC",
    "MPOI2EDC",
    "TVARSEDC",
    "X73_EDC",
    "P2E_SEDC",
    "MLH_SEDC",
    "P",
    "ADHE_EDC",
    "EGT16EDC",
    "PWG_EDC",
    "ALPHASOL",
    "MLH_AKT",
    "ML_DEGUF",
    "KW_MEAN",
    "ME",
    "ME_EDC",
    "BE",
    "PZ_MAX",
    "GER_INM",
    "PME",
    "PMI",
    "PMI_HD",
    "PMI_LW",
    "PMI_S",
    "INM_R1",
    "LAMA",
    "BLOWVAL",
    "VELO_X",
    "VELO_Y",
    "T0",
    "T1",
    "T2_L1",
    "T2_I1",
    "T2_E1",
    "T_ARF1",
    "T_ARF2",
    "T3_A1",
    "T4_A1",
    "TOEL",
    "TKR_R",
    "P0_ABS",
    "P1_ABS",
    "P2_L1ABS",
    "P2_I1ABS",
    "P2_E1ABS",
    "P_ARF1AB",
    "P_ARF2AB",
    "P3_A1ABS",
    "P4_A1ABS",
    "POEL",
    "SZ_H",
    "OPAC_DIG",
    "MS_CoDc",
    "HC",
    "CO",
    "CO2",
    "O2",
    "NOX",
    "NO1",
    "ABG_MS_1",
    "CO2_L1_9",
    "LB",
    "LBCO2",
    "LBV",
    "HC_L1_1",
    "CO_L1_1",
    "CO2_L1_1",
    "O2_L1_1",
    "NOX_L1_1",
    "NO1_L1_1",
]

# PUMA column -> canonical parameter name for limits
COLUMN_ALIAS_MAP: Dict[str, str] = {
    "P0_ABS": "P0",
    "P1_ABS": "P1",
    "P2_L1ABS": "P2_L1",
    "P2_I1ABS": "P2_I1",
    "P2_E1ABS": "P2_E1",
    "P_ARF1AB": "P_ARF1",
    "P_ARF2AB": "P_ARF2",
    "P3_A1ABS": "P3_A1",
    "P4_A1ABS": "P4_A1",
    "NO1": "NOX",
    "NO1_L1_1": "NOX_L1_1",
    "T2_I1.1": "T2_I1",
    "TW_R.1": "TW_R",
    "TKR_Z.1": "TKR_Z",
    "P4_A1ABS.1": "P4_A1",
    "P4_A1.1": "P4_A1",
}

# parameter_name -> metadata
PARAMETER_INFO: Dict[str, Dict[str, str]] = {
    "T0": {"desc": "Air inlet before Filter", "category": "Air intake", "type": "temperature", "unit": "°C"},
    "T1": {"desc": "Air inlet after filter", "category": "Air intake", "type": "temperature", "unit": "°C"},
    "T2_L1": {"desc": "Air inlet Before Turbo", "category": "Air intake", "type": "temperature", "unit": "°C"},
    "T2_I1": {"desc": "Air inlet After Intercooler", "category": "Air intake", "type": "temperature", "unit": "°C"},
    "T2_E1": {"desc": "Air inlet at manifold after EGR mixing", "category": "Air intake", "type": "temperature", "unit": "°C"},
    "T_ARF1": {"desc": "Exhaust EGR before EGR cooler", "category": "EGR", "type": "temperature", "unit": "°C"},
    "T_ARF2": {"desc": "Exhaust EGR after EGR cooler", "category": "EGR", "type": "temperature", "unit": "°C"},
    "T3_A1": {"desc": "Before Turbo Charger", "category": "Exhaust", "type": "temperature", "unit": "°C"},
    "T4_A1": {"desc": "After Turbo Charger", "category": "Exhaust", "type": "temperature", "unit": "°C"},
    "TOEL": {"desc": "Lube oil", "category": "Lube oil", "type": "temperature", "unit": "°C"},
    "TW_R": {"desc": "Coolant Return from engine", "category": "Coolant", "type": "temperature", "unit": "°C"},
    "TKR_Z": {"desc": "Fuel Return from engine", "category": "Fuel", "type": "temperature", "unit": "°C"},
    "TKR_R": {"desc": "Fuel Inlet to engine", "category": "Fuel", "type": "temperature", "unit": "°C"},
    "P0": {"desc": "Air inlet before Filter", "category": "Air intake", "type": "pressure", "unit": "mbar"},
    "P1": {"desc": "Air inlet after filter", "category": "Air intake", "type": "pressure", "unit": "mbar"},
    "P2_L1": {"desc": "Air inlet Before Turbo", "category": "Air intake", "type": "pressure", "unit": "mbar"},
    "P2_I1": {"desc": "Air inlet After Intercooler", "category": "Air intake", "type": "pressure", "unit": "mbar"},
    "P2_E1": {"desc": "Air inlet at manifold after EGR mixing", "category": "Air intake", "type": "pressure", "unit": "mbar"},
    "P_ARF1": {"desc": "Exhaust EGR before EGR cooler", "category": "EGR", "type": "pressure", "unit": "mbar"},
    "P_ARF2": {"desc": "Exhaust EGR after EGR cooler", "category": "EGR", "type": "pressure", "unit": "mbar"},
    "P3_A1": {"desc": "Before Turbo Charger", "category": "Exhaust", "type": "pressure", "unit": "mbar"},
    "P4_A1": {"desc": "After Turbo Charger", "category": "Exhaust", "type": "pressure", "unit": "mbar"},
    "POEL": {"desc": "Lube oil", "category": "Lube oil", "type": "pressure", "unit": "bar"},
    "PZ_MAX1": {"desc": "Combustion Pressure cylinder 1", "category": "Combustion", "type": "pressure", "unit": "bar"},
    "N": {"desc": "Engine speed", "category": "Set", "type": "set", "unit": "1/min"},
    "MD": {"desc": "Torque", "category": "Set", "type": "set", "unit": "Nm"},
    "P": {"desc": "Power", "category": "Performance", "type": "set", "unit": "kW"},
    "PZ_MAX": {"desc": "Peak cylinder pressure", "category": "Combustion", "type": "pressure", "unit": "bar"},
    "PME": {"desc": "Brake mean effective pressure", "category": "Performance", "type": "set", "unit": "bar"},
    "LAMA": {"desc": "Lambda", "category": "Emissions", "type": "emission", "unit": ""},
    "Lambda": {"desc": "Lambdameter", "category": "Emissions", "type": "emission", "unit": "°C"},
    "HC": {"desc": "Hydrocarbons", "category": "Post-Cat Emissions", "type": "emission", "unit": "ppm"},
    "CO": {"desc": "Carbon monoxide", "category": "Post-Cat Emissions", "type": "emission", "unit": "ppm"},
    "CO2": {"desc": "Carbon dioxide", "category": "Post-Cat Emissions", "type": "emission", "unit": "%"},
    "O2": {"desc": "Oxygen", "category": "Post-Cat Emissions", "type": "emission", "unit": "%"},
    "NOX": {"desc": "Nitrogen oxides", "category": "Post-Cat Emissions", "type": "emission", "unit": "ppm"},
    "SZ_H": {"desc": "Soot number", "category": "Post-Cat Emissions", "type": "emission", "unit": "FSN"},
    "HC_L1_1": {"desc": "Pre-cat HC", "category": "Pre-Cat Emissions", "type": "emission", "unit": "ppmC"},
    "CO_L1_1": {"desc": "Pre-cat CO", "category": "Pre-Cat Emissions", "type": "emission", "unit": "ppm"},
    "CO2_L1_1": {"desc": "Pre-cat CO2", "category": "Pre-Cat Emissions", "type": "emission", "unit": "%"},
    "NOX_L1_1": {"desc": "Pre-cat NOx", "category": "Pre-Cat Emissions", "type": "emission", "unit": "ppm"},
}


def canonical_column_name(col: str) -> str:
    """Map raw dataframe column to canonical parameter name."""
    s = str(col).strip()
    if s in COLUMN_ALIAS_MAP:
        return COLUMN_ALIAS_MAP[s]
    return s


def parameter_defaults(name: str) -> Tuple[str, str, str, str]:
    """Return (description, category, ptype, unit) for seeding limits."""
    info = PARAMETER_INFO.get(name)
    if not info:
        return ("", "Other", "other", "")
    return (
        info["desc"],
        info["category"],
        info["type"],
        info.get("unit", ""),
    )
